# GUIDE
# mkdocs build
# mkdocs serve
# mkdocs -h
site_name: Kenan's Website
theme: # https://www.youtube.com/watch?v=xlABhbnNrfI
  name: material
  font:
    text: Roboto
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue gray
      accent: light blue
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: green
      accent: deep purple

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:banalkenan@gmail.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kenan-banal-1392472a9/
    - icon: fontawesome/brands/github
      link: https://github.com/kenaniscoding/mkdocs-resume
extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2025 Kenan Banal
